# Generated by Django 3.0.4 on 2020-05-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('channel_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.CharField(blank=True, max_length=45, null=True)),
                ('source', models.CharField(blank=True, max_length=45, null=True)),
                ('target', models.CharField(blank=True, max_length=45, null=True)),
                ('start', models.TextField(blank=True, null=True)),
                ('end', models.TextField(blank=True, null=True)),
                ('start_point_id', models.CharField(blank=True, max_length=45, null=True)),
                ('end_point_id', models.CharField(blank=True, max_length=45, null=True)),
                ('start_point', models.TextField(blank=True, null=True)),
                ('end_point', models.TextField(blank=True, null=True)),
                ('shape', models.CharField(blank=True, max_length=45, null=True)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'edge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('size', models.CharField(blank=True, max_length=45, null=True)),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('filepath', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=120, null=True)),
                ('owner', models.CharField(blank=True, max_length=120, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'graph',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('raw_script_name', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('shape', models.CharField(blank=True, max_length=45, null=True)),
                ('size', models.CharField(blank=True, max_length=45, null=True)),
                ('color', models.CharField(blank=True, max_length=45, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'node',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('label', models.CharField(blank=True, max_length=45, null=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'node_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('raw_script_name', models.TextField(blank=True, null=True)),
                ('shape', models.CharField(blank=True, max_length=45, null=True)),
                ('size', models.CharField(blank=True, max_length=45, null=True)),
                ('color', models.CharField(blank=True, max_length=45, null=True)),
                ('node_detail', models.TextField(blank=True, null=True)),
                ('point_detail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'node_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PointDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('proportion', models.FloatField(blank=True, null=True)),
                ('func', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'point_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
